abc-laravel8-master/routes/web.php
<?php

use App\Http\Controllers\AdminLoginController;
use App\Http\Controllers\NhomsanphamController;
use App\Http\Controllers\SanphamController;
use App\Http\Controllers\UserManagementController;
use App\Http\Controllers\RegistrationController;
use App\Http\Middleware\CheckAdminLogin;
use Illuminate\Support\Facades\Route;

use App\Http\Livewire\TestComponent;
use App\Http\Middleware\CheckCustomer;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/admin/login', [AdminLoginController::class,'getlogin'])->name('admin.getlogin');
Route::post('/admin/login', [AdminLoginController::class,'postlogin'])->name('admin.postlogin');
Route::get('/admin/logout', [AdminLoginController::class,'getlogout'])->name('admin.getlogout');

// ->middleware([CheckAdminLogin::class])
Route::prefix('admin')->name('admin.')->middleware([CheckAdminLogin::class])->group(function(){
    Route::get('/', [AdminLoginController::class, 'dashboard'])->name('dashboard');

    Route::get('/file', function () {
        return view('admin.file');
    })->name('file');

    Route::resources([
        'nhomsanpham' => NhomsanphamController::class,
        'sanpham' => SanphamController::class,
        'usermanagement' => UserManagementController::class,
    ]);

});

Route::get('/', function () {
    return view('site.index');
})->name('home');

Route::get('/shop', function () {
    return view('site.shop');
})->name('shop');

Route::get('/cart', function () {
    return view('site.cart');
})->name('cart');
Route::get('/productdetail/{param}',App\Http\Livewire\ProductDetail::class)->name('productdetail');

Route::get('/checkout',App\Http\Livewire\CheckOut::class)->name('checkout');
Route::get('/blog1',App\Http\Livewire\Blog::class)->name('blog');
Route::get('/contact',App\Http\Livewire\Contact::class)->name('contact');
Route::get('/blog-detail',App\Http\Livewire\BlogDetail::class)->name('blog-detail');
Route::get("/register", [RegistrationController::class, 'create'])->name('register');
Route::post("/register/create", [RegistrationController::class, 'store']);
Route::get('/thanhtoan',App\Http\Livewire\Testthanhtoan::class)->name('thanhtoan');

abc-laravel8-master/app/Models/Sanpham.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Nhomsanpham;
use App\Models\Review;
class Sanpham extends Model
{
    use HasFactory;
    protected $table='sanpham';
    protected $fillable=['ten','mota','gia','giaban','anh','danhsachanh','trangthai','uutien','nhomsanphamid'];

    public function nhomsanpham(){
        return Nhomsanpham::find($this->nhomsanphamid);
    }
    public function reviews()
    {
        return $this->hasMany(Review::class,'product_id');//collection

    }
}

abc-laravel8-master/app/Http/Controllers/SanphamController.php
<?php

namespace App\Http\Controllers;

use App\Models\Sanpham;
use Illuminate\Http\Request;
use App\Models\Nhomsanpham;
use Illuminate\Support\Facades\File;

class SanphamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if ($key=request()->key){
            $data = Sanpham::where('ten', 'like', '%'.$key.'%')->orderby('uutien','DESC')->paginate(5);
        }
        else {
            $data = Sanpham::orderby('uutien','DESC')->paginate(5);
        }

        return view('admin.sanpham.index',['data'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $nhomsanphams=Nhomsanpham::orderby('ten')->where('trangthai',1)->select('id','ten')->get();
        return view('admin.sanpham.create', compact('nhomsanphams'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'ten'=>'required|unique:sanpham',
            'gia'=>'required',
            'uutien'=>'required',
        ],
        [
            'ten.required' => 'Cần nhập tên nhóm sản phẩm',
            'ten.unique' => 'Tên nhóm sản phẩm cần duy nhất',
            'gia.required' => 'Cần nhập giá sản phẩm',
            'uutien.required' => "Cần nhập mức độ ưu tiên",

        ]
        );
        if ($request->has('file_upload')){
            $file=$request->file_upload;
            $ext=$file->extension();

            $file_name=time().'-sp.'.$ext;

            $file->move(public_path('uploads'), $file_name);
            $request->merge(['anh'=>$file_name]);
        }

        if(Sanpham::create($request->all())){
            return redirect()->route('admin.sanpham.index')->with('success', 'Thêm mới sản phẩm thành công.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Sanpham  $sanpham
     * @return \Illuminate\Http\Response
     */
    public function show(Sanpham $sanpham)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Sanpham  $sanpham
     * @return \Illuminate\Http\Response
     */
    public function edit(Sanpham $sanpham)
    {
        $nhomsanphams=Nhomsanpham::orderby('ten')->where('trangthai',1)->select('id','ten')->get();

        return view('admin.sanpham.edit', ['sanpham'=>$sanpham, 'nhomsanphams'=>$nhomsanphams]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Sanpham  $sanpham
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sanpham $sanpham)
    {
        $request->validate([
            'ten'=>'required|unique:nhomsanpham,ten,'.$sanpham->id,
            'gia'=>'required',
            'uutien'=>'required',
        ],
        [
            'ten.required' => 'Cần nhập tên nhóm sản phẩm',
            'ten.unique' => 'Tên nhóm sản phẩm cần duy nhất',
            'gia.required' => 'Cần nhập giá sản phẩm',
            'uutien.required' => "Cần nhập mức độ ưu tiên",

        ]
        );

        $deleteimage=false;
        $oldimage=public_path('uploads/'.$sanpham->anh);

        if ($request->has('file_upload')){
            $file=$request->file_upload;
            $ext=$file->extension();

            $file_name=time().'-sp.'.$ext;

            $file->move(public_path('uploads'), $file_name);
            $request->merge(['anh'=>$file_name]);
            $deleteimage=true;
        }else{
            $request->merge(['anh'=>$sanpham->anh]);
        }
        if($sanpham->update($request->only('ten','mota','danhsachanh','nhomsanphamid','gia','giaban','anh','trangthai','uutien'))){
            if ($deleteimage){
                File::delete($oldimage);
            }
            return redirect()->route('admin.sanpham.index')->with('success','Cập nhật sản phẩm thành công.');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Sanpham  $sanpham
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sanpham $sanpham)
    {
        $sanpham->delete();
        return redirect()->route('admin.sanpham.index')->with('success','Xóa bản ghi thành công.');
    }
}

abc-laravel8-master/resources/views/admin/sanpham/create.blade.php
@extends('layouts.admin')

@section('title', 'Thêm mới sản phẩm')

@section('content')

<form action="{{route('admin.sanpham.store')}}" method='post' enctype="multipart/form-data">
  @csrf
  <div class="row">
    <div class="col-md-8">

      <div class="form-group">
        <label for="ten">Tên</label>
        <input type="text" class="form-control" name="ten" id="ten" aria-describedby="helpId"
          placeholder="Tên sản phẩm">
        @error('ten')
        <small class="text-help text-danger">{{$message}}</small>
        @enderror
      </div>
      <div class="form-group">
        <label for="mota">Mô tả</label>
        <textarea class="form-control" name="mota" id="mota" rows="6" placeholder='Mô tả sản phẩm'></textarea>
      </div>
      <div class="form-group">
        <label for="danhsachanh">Danh sách ảnh
          <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#model_list">
            <i class="fa fa-folder-open"></i>
          </button>
        </label>
        <!-- <input type="text" class="form-control" name="danhsachanh" id="danhsachanh" aria-describedby="helpId"
          placeholder="Danh sách ảnh"> -->

        <input type="hidden" id="danhsachanh" name="danhsachanh">

        <div class="row" id="show_danhsachanh">
        </div>
      </div>

    </div>
    <div class="col-md-4">
      <div class="form-group">
        <label for="nhomsanphamid">Nhóm sản phẩm</label>
        <select class="form-control" name="nhomsanphamid" id="nhomsanphamid">
          @foreach ($nhomsanphams as $nsp )
          <option value={{$nsp->id}}>{{$nsp->ten}}</option>
          @endforeach

        </select>
      </div>
      <div class="form-group">
        <label for="gia">Giá</label>
        <input type="number" class="form-control" name="gia" id="gia" aria-describedby="helpId" placeholder="Giá">
        @error('gia')
        <small class="text-help text-danger">{{$message}}</small>
        @enderror
      </div>
      <div class="form-group">
        <label for="giaban">Giá bán</label>
        <input type="number" class="form-control" name="giaban" id="giaban" aria-describedby="helpId"
          placeholder="Giá bán">
      </div>
      <div class="form-group">
        <label for="file_upload">Ảnh</label>
        <input type="file" class="form-control" name="file_upload" id="file_upload" aria-describedby="helpId"
          placeholder="Ảnh sản phẩm">
      </div>
      <div class="form-group">
        <label for="trangthai">Trạng thái</label>
        <select class="form-control" name="trangthai" id="trangthai">
          <option value=1>Hoạt động</option>
          <option value=0>Không hoạt động</option>
        </select>
      </div>
      <div class="form-group">
        <label for="uutien">Mức ưu tiên</label>
        <input type="number" class="form-control" name="uutien" id="uutien" aria-describedby="helpId"
          placeholder="Mức ưu tiên">
        @error('uutien')
        <small class="text-help text-danger">{{$message}}</small>
        @enderror
      </div>

      <button type="submit" class="btn btn-primary">Thêm mới</button>
    </div>
  </div>
</form>


<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="model_list" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
  <div class="modal-dialog" role="document" style="max-width:900px">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <iframe src="{{url('file/dialog.php?field_id=danhsachanh')}}"
          style="width:100%; height:500px; overflow-y: auto; border:none"></iframe>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


@endsection

@section('css')
<!-- summernote -->
<link rel="stylesheet" href="{{url('adminlte123')}}/plugins/summernote/summernote-bs4.min.css">
@endsection

@section('js')
<!-- Summernote -->
<script src="{{url('adminlte123')}}/plugins/summernote/summernote-bs4.min.js"></script>

<!-- Page specific script -->
<script>
$(function() {
  // Summernote
  $('#mota').summernote({
    height: 200,
    placeholder: "Mô tả sản phẩm"
  })
})


$("#model_list").on('hidden.bs.modal', event => {
  var _links = $('input#danhsachanh').val();
  try {
    var _image_list = JSON.parse(_links);
  } catch (error) {
    var _image_list = [_links];
  }
  var _html = '';
  for (let i in _image_list) {
    let _img = "{{url('thumbs')}}" + '/' + _image_list[i];
    _html += '<div class="col-sm-2">';
    _html += '<img src="' + _img + '" alt="" style="width:100%">';
    _html += '</div>'
  }
  $('#show_danhsachanh').html(_html);
});
</script>
@endsection

abc-laravel8-master/resources/views/admin/sanpham/edit.blade.php
@extends('layouts.admin')

@section('title', 'Thêm mới sản phẩm')

@section('content')

<form action="{{route('admin.sanpham.update', $sanpham->id)}}" method='post' enctype="multipart/form-data">
    @csrf @method('PUT')
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="nhomsanphamid">Nhóm sản phẩm</label>
                <select class="form-control" name="nhomsanphamid" id="nhomsanphamid">
                    @foreach ($nhomsanphams as $nsp )
                    <option value={{$nsp->id}} @if ($sanpham->nhomsanphamid==$nsp->id) selected='selected' @endif>{{$nsp->ten}}</option>
                    @endforeach

                </select>
            </div>
            <div class="form-group">
                <label for="ten">Tên</label>
                <input type="text" value="{{$sanpham->ten}}" class="form-control" name="ten" id="ten" aria-describedby="helpId" placeholder="Tên sản phẩm">
                @error('ten')
                <small class="text-help text-danger">{{$message}}</small>
                @enderror
            </div>
            <div class="form-group">
                <label for="mota">Mô tả</label>
                <textarea class="form-control" name="mota" id="mota" rows="6" placeholder='Mô tả sản phẩm' rows=8>{{$sanpham->mota}}</textarea>

            </div>
            <div class="form-group">
                <label for="danhsachanh">Danh sách ảnh</label>
                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#model_list">
                    <i class="fa fa-folder-open"></i>
                </button>
                </label>
                <!-- <input type="text" class="form-control" name="danhsachanh" id="danhsachanh" aria-describedby="helpId"
          placeholder="Danh sách ảnh"> -->

                <input type="hidden" id="danhsachanh" name="danhsachanh" value="{{$sanpham->danhsachanh}}">

                <div class="row" id="show_danhsachanh">
                </div>
            </div>


        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="gia">Giá</label>
                <input type="number" value="{{$sanpham->gia}}" class="form-control" name="gia" id="gia" aria-describedby="helpId" placeholder="Giá">
                @error('gia')
                <small class="text-help text-danger">{{$message}}</small>
                @enderror
            </div>
            <div class="form-group">
                <label for="giaban">Giá bán</label>
                <input type="number" value="{{$sanpham->giaban}}" class="form-control" name="giaban" id="giaban" aria-describedby="helpId" placeholder="Giá bán">
            </div>
            <div class="form-group">
                <label for="file_upload">Ảnh</label>
                @if($sanpham->anh)
                <img id="original" src="{{ url('uploads/'.$sanpham->anh) }}" height="100" width="100">
                @endif
                <input type="file" class="form-control" name="file_upload" id="file_upload" aria-describedby="helpId" placeholder="Ảnh sản phẩm">
            </div>
            <div class="form-group">
                <label for="trangthai">Trạng thái</label>
                <select class="form-control" name="trangthai" id="trangthai">
                    <option value=1 @if ($sanpham->trangthai==1) selected='selected' @endif>Hoạt động</option>
                    <option value=0 @if ($sanpham->trangthai==0) selected='selected' @endif>Không hoạt động</option>
                </select>
            </div>
            <div class="form-group">
                <label for="uutien">Mức ưu tiên</label>
                <input type="number" value="{{$sanpham->uutien}}" class="form-control" name="uutien" id="uutien" aria-describedby="helpId" placeholder="Mức ưu tiên">
                @error('uutien')
                <small class="text-help text-danger">{{$message}}</small>
                @enderror
            </div>

            <button type="submit" class="btn btn-primary">Cập nhật</button>

        </div>
    </div>
</form>

<!-- Modal -->
<div class="modal fade" id="model_list" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
  <div class="modal-dialog" role="document" style="max-width:900px">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <iframe src="{{url('file/dialog.php?field_id=danhsachanh')}}"
          style="width:100%; height:500px; overflow-y: auto; border:none"></iframe>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

@endsection

@section('css')
<!-- summernote -->
<link rel="stylesheet" href="{{url('adminlte123')}}/plugins/summernote/summernote-bs4.min.css">
@endsection

@section('js')
<!-- Summernote -->
<script src="{{url('adminlte123')}}/plugins/summernote/summernote-bs4.min.js"></script>

<!-- Page specific script -->
<script>
    $(function() {
        // Summernote
        $('#mota').summernote({
            height: 200,
            placeholder: "Mô tả sản phẩm"
        })
    })

    function refresh_danhsachanh(){
        var _links = $('input#danhsachanh').val();
        try{
            var _image_list = JSON.parse(_links);
        }catch(error){
            var _image_list = [_links];
        }
        var _html = '';
        for (let i in _image_list) {
            let _img = "{{url('thumbs')}}" + '/' + _image_list[i];
            _html += '<div class="col-sm-2">';
            _html += '<img src="' + _img + '" alt="" style="width:100%">';
            _html += '</div>'
        }

        $('#show_danhsachanh').html(_html);
    }

    $(function() {
        refresh_danhsachanh();
    });

    $("#model_list").on('hidden.bs.modal', event => {
        refresh_danhsachanh();
    });
</script>
@endsection

abc-laravel8-master/resources/views/admin/sanpham/index.blade.php
@extends('layouts.admin')

@section('title','Sản phẩm')

@section('content')
    <div class="row my-2">
        <div class="col-md-8">
            <form class="form-inline">
                <div class="form-group">
                    <input type="text" name="key" value="{{request()->key}}" class="form-control" placeholder="Từ khóa" aria-describedby="helpId">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                </div>
            </form>
        </div>
        <div class="col-md-4 text-right">
            <a class="btn btn-primary" href="{{route('admin.sanpham.create')}}" role="button">Thêm mới</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Tên</th>
                <th>Giá</th>
                <th>Giá bán</th>
                <th>Trạng thái</th>
                <th>Mức ưu tiên</th>
                <th class='text-right'>Hành động</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $d)
            <tr>
                <td scope="row">{{$d->id}}</td>
                <td>{{$d->ten}}</td>
                <td>{{$d->gia}}</td>
                <td>{{$d->giaban}}</td>
                <td>
                    @if ($d->trangthai==1)
                        <span class="badge badge-primary">Hoạt động</span>
                    @else
                        <span class="badge badge-danger">Không hoạt động</span>
                    @endif
                </td>
                <td>{{$d->uutien}}</td>
                <td class="text-right">
                    <a name="" id="" class="btn btn-sm btn-primary" href="{{route('admin.sanpham.edit', $d->id)}}" role="button"><i class="fa fa-edit"></i></a>
                    <a name="" id="" class="btn btn-sm btn-danger btndelete" href="{{route('admin.sanpham.destroy',$d->id)}}" role="button"><i class="fa fa-trash"></i> </a>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    {{$data->appends(Request::all())->links()}}

    <form id='formdelete' action="" method="post">
        @csrf @method('DELETE')
    </form>
@endsection

@section('js')
<script>
    $(".btndelete").click(function(ev){
        ev.preventDefault();
        let _href=$(this).attr('href');
        $("form#formdelete").attr('action',_href);
        if (confirm('Bạn muốn xóa bản ghi này không?'))
        {
            $("form#formdelete").submit();
        }
    });
</script>
@endsection