abc-laravel8-master/routes/web.php
<?php

use App\Http\Controllers\AdminLoginController;
use App\Http\Controllers\NhomsanphamController;
use App\Http\Controllers\SanphamController;
use App\Http\Controllers\UserManagementController;
use App\Http\Controllers\RegistrationController;
use App\Http\Middleware\CheckAdminLogin;
use Illuminate\Support\Facades\Route;

use App\Http\Livewire\TestComponent;
use App\Http\Middleware\CheckCustomer;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/admin/login', [AdminLoginController::class,'getlogin'])->name('admin.getlogin');
Route::post('/admin/login', [AdminLoginController::class,'postlogin'])->name('admin.postlogin');
Route::get('/admin/logout', [AdminLoginController::class,'getlogout'])->name('admin.getlogout');

// ->middleware([CheckAdminLogin::class])
Route::prefix('admin')->name('admin.')->middleware([CheckAdminLogin::class])->group(function(){
    Route::get('/', [AdminLoginController::class, 'dashboard'])->name('dashboard');

    Route::get('/file', function () {
        return view('admin.file');
    })->name('file');

    Route::resources([
        'nhomsanpham' => NhomsanphamController::class,
        'sanpham' => SanphamController::class,
        'usermanagement' => UserManagementController::class,
    ]);

});

Route::get('/', function () {
    return view('site.index');
})->name('home');

Route::get('/shop', function () {
    return view('site.shop');
})->name('shop');

Route::get('/cart', function () {
    return view('site.cart');
})->name('cart');
Route::get('/productdetail/{param}',App\Http\Livewire\ProductDetail::class)->name('productdetail');

Route::get('/checkout',App\Http\Livewire\CheckOut::class)->name('checkout');
Route::get('/blog1',App\Http\Livewire\Blog::class)->name('blog');
Route::get('/contact',App\Http\Livewire\Contact::class)->name('contact');
Route::get('/blog-detail',App\Http\Livewire\BlogDetail::class)->name('blog-detail');
Route::get("/register", [RegistrationController::class, 'create'])->name('register');
Route::post("/register/create", [RegistrationController::class, 'store']);
Route::get('/thanhtoan',App\Http\Livewire\Testthanhtoan::class)->name('thanhtoan');

abc-laravel8-master/app/Models/Nhomsanpham.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Nhomsanpham extends Model
{
    use HasFactory;
    protected $table='nhomsanpham';
    protected $fillable=['ten', 'trangthai', 'uutien'];

    public function sanphams(){
        return $this->hasMany(Sanpham::class, 'nhomsanphamid','id');
    }
}

abc-laravel8-master/app/Http/Controllers/NhomsanphamController.php
<?php

namespace App\Http\Controllers;

use App\Models\Nhomsanpham;
use Illuminate\Http\Request;

class NhomsanphamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if ($key=request()->key){
            $data = Nhomsanpham::where('ten', 'like', '%'.$key.'%')->orderby('uutien','DESC')->paginate(5);
        }
        else {
            $data = Nhomsanpham::orderby('uutien','DESC')->paginate(5);
        }

        return view('admin.nhomsanpham.index',['data'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.nhomsanpham.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'ten'=>'required|unique:nhomsanpham,ten',
            'uutien'=>'required',
        ],
        [
            'ten.required' => 'Cần nhập tên nhóm sản phẩm',
            'ten.unique' => 'Tên nhóm sản phẩm cần duy nhất',
            'uutien.required' => "Cần nhập mức độ ưu tiên",

        ]
        );

        if (Nhomsanpham::create($request->all())){
            return redirect()->route('admin.nhomsanpham.index')->with('success','Thêm mới thành công.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Nhomsanpham  $nhomsanpham
     * @return \Illuminate\Http\Response
     */
    public function show(Nhomsanpham $nhomsanpham)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Nhomsanpham  $nhomsanpham
     * @return \Illuminate\Http\Response
     */
    public function edit(Nhomsanpham $nhomsanpham)
    {
        return view('admin.nhomsanpham.edit',["nhomsanpham"=>$nhomsanpham]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Nhomsanpham  $nhomsanpham
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Nhomsanpham $nhomsanpham)
    {
        $request->validate([
            'ten'=>'required|unique:nhomsanpham,ten,'.$nhomsanpham->id,
            'uutien'=>'required',
        ],
        [
            'ten.required' => 'Cần nhập tên nhóm sản phẩm',
            'ten.unique' => 'Tên nhóm sản phẩm cần duy nhất',
            'uutien.required' => "Cần nhập mức độ ưu tiên",

        ]
        );

        if ($nhomsanpham->update($request->all())){
            return redirect()->route('admin.nhomsanpham.index')->with('success','Thêm mới thành công.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Nhomsanpham  $nhomsanpham
     * @return \Illuminate\Http\Response
     */
    public function destroy(Nhomsanpham $nhomsanpham)
    {
        //
        if ($nhomsanpham->sanphams()->count()>0){
            return redirect()->route('admin.nhomsanpham.index')->with('error','Xóa bản ghi không thành công do có chứa sản phẩm.');
        }
        else{
            $nhomsanpham->delete();
            return redirect()->route('admin.nhomsanpham.index')->with('success','Xóa bản ghi thành công.');
        }

    }
}

abc-laravel8-master/resources/views/admin/nhomsanpham/create.blade.php
@extends('layouts.admin')

@section('title','Thêm mới nhóm sản phẩm')

@section('content')
    <form action="{{route('admin.nhomsanpham.store')}}" method='post'>
        @csrf
        <div class="form-group">
          <label for="tennhomsanpham">Tên nhóm sản phẩm</label>
          <input type="text" value="{{old('ten')}}" class="form-control" name="ten" id="tennhomsanpham" aria-describedby="helpId" placeholder="Tên nhóm sản phẩm">
          @error('ten')
          <small class="text-danger">{{$message}}</small>
          @enderror
        </div>
        <div class="form-group">
          <label for="trangthai">Trạng thái</label>
          <select class="form-control" name="trangthai" id="trangthai">
            <option value=1 @if (old('trangthai')==1) selected='selected' @endif>Hoạt động</option>
            <option value=0 @if (old('trangthai')!=null and old('trangthai')==0) selected='selected' @endif>Không hoạt động</option>
          </select>
        </div>
        <div class="form-group">
          <label for="uutien">Mức ưu tiên</label>
          <input type="number" value="{{old('uutien')}}" class="form-control" name="uutien" id="uutien" aria-describedby="helpId" placeholder="Mức ưu tiên">
          @error('uutien')
          <small class="text-danger">{{$message}}</small>
          @enderror
        </div>
        <button type="submit" class="btn btn-primary">Thêm mới</button>
    </form>
@endsection

abc-laravel8-master/resources/views/admin/nhomsanpham/edit.blade.php
@extends('layouts.admin')

@section('title','Cập nhật nhóm sản phẩm')

@section('content')
    <form action="{{route('admin.nhomsanpham.update',$nhomsanpham->id)}}" method='post'>
        @csrf @method('PUT')
        <div class="form-group">
          <label for="tennhomsanpham">Tên nhóm sản phẩm</label>
          <input type="text" value="{{$nhomsanpham->ten}}" class="form-control" name="ten" id="tennhomsanpham" aria-describedby="helpId" placeholder="Tên nhóm sản phẩm">
          @error('ten')
          <small class="text-danger">{{$message}}</small>
          @enderror
        </div>
        <div class="form-group">
          <label for="trangthai">Trạng thái</label>
          <select class="form-control" name="trangthai" id="trangthai">
            <option value=1 @if ($nhomsanpham->trangthai==1) selected='selected' @endif>Hoạt động</option>
            <option value=0 @if ($nhomsanpham->trangthai==0) selected='selected' @endif>Không hoạt động</option>
          </select>
        </div>
        <div class="form-group">
          <label for="uutien">Mức ưu tiên</label>
          <input type="number" value="{{$nhomsanpham->uutien}}" class="form-control" name="uutien" id="uutien" aria-describedby="helpId" placeholder="Mức ưu tiên">
          @error('uutien')
          <small class="text-danger">{{$message}}</small>
          @enderror
        </div>
        <button type="submit" class="btn btn-primary">Cập nhật</button>
    </form>
@endsection

abc-laravel8-master/resources/views/admin/nhomsanpham/index.blade.php
@extends('layouts.admin')

@section('title','Nhóm sản phẩm')

@section('content')
    <div class="row my-2">
        <div class="col-md-8">
            <form class="form-inline">
                <div class="form-group">
                    <input type="text" name="key" value="{{request()->key}}" class="form-control" placeholder="Từ khóa" aria-describedby="helpId">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                </div>
            </form>
        </div>
        <div class="col-md-4 text-right">
            <a class="btn btn-primary" href="{{route('admin.nhomsanpham.create')}}" role="button">Thêm mới</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Tên</th>
                <th>Số sản phẩm</th>
                <th>Trạng thái</th>
                <th>Mức ưu tiên</th>
                <th class='text-right'>Hành động</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $d)
            <tr>
                <td scope="row">{{$d->id}}</td>
                <td>{{$d->ten}}</td>
                <td>{{$d->sanphams()->count()}}</td>
                <td>
                    @if ($d->trangthai==1)
                        <span class="badge badge-primary">Hoạt động</span>
                    @else
                        <span class="badge badge-danger">Không hoạt động</span>
                    @endif
                </td>
                <td>{{$d->uutien}}</td>
                <td class="text-right">
                    <a name="" id="" class="btn btn-sm btn-primary" href="{{route('admin.nhomsanpham.edit', $d->id)}}" role="button"><i class="fa fa-edit"></i></a>
                    <a name="" id="" class="btn btn-sm btn-danger btndelete" href="{{route('admin.nhomsanpham.destroy',$d->id)}}" role="button"><i class="fa fa-trash"></i> </a>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    {{$data->appends(Request::all())->links()}}

    <form id='formdelete' action="" method="post">
        @csrf @method('DELETE')
    </form>
@endsection

@section('js')
<script>
    $(".btndelete").click(function(ev){
        ev.preventDefault();
        let _href=$(this).attr('href');
        $("form#formdelete").attr('action',_href);
        if (confirm('Bạn muốn xóa bản ghi này không?'))
        {
            $("form#formdelete").submit();
        }
    });
</script>
@endsection